import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    // { type: 'autogenerated', dirName: '.' }
    {
      type: 'category',
      collapsed: false,
      label: 'Introduction',
      items: [
        'introduction/getting-started',
        'introduction/how-does-reselect-work',
        'introduction/v5-summary'
      ]
    },
    {
      type: 'category',
      collapsed: false,
      label: 'API',
      items: [
        'api/createSelector',
        'api/createSelectorCreator',
        'api/createStructuredSelector',
        'api/development-only-stability-checks',
        {
          type: 'category',
          collapsed: false,
          label: 'Memoization Functions',
          items: [
            'api/lruMemoize',
            'api/weakMapMemoize',
            'api/unstable_autotrackMemoize'
          ]
        }
      ]
    },

    {
      type: 'category',
      label: 'Using Reselect',
      items: [
        'usage/best-practices',
        'usage/common-mistakes',
        'usage/handling-empty-array-results'
      ]
    },
    'FAQ',
    'external-references',
    'related-projects',
    'codemods'
  ]
}

export default sidebars
